// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package project.group16.entity;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import project.group16.entity.FinanceDepertment;
import project.group16.entity.FinanceDepertmentDataOnDemand;
import project.group16.entity.FinanceDepertmentIntegrationTest;

privileged aspect FinanceDepertmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FinanceDepertmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FinanceDepertmentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FinanceDepertmentIntegrationTest: @Transactional;
    
    @Autowired
    private FinanceDepertmentDataOnDemand FinanceDepertmentIntegrationTest.dod;
    
    @Test
    public void FinanceDepertmentIntegrationTest.testCountFinanceDepertments() {
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to initialize correctly", dod.getRandomFinanceDepertment());
        long count = FinanceDepertment.countFinanceDepertments();
        Assert.assertTrue("Counter for 'FinanceDepertment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FinanceDepertmentIntegrationTest.testFindFinanceDepertment() {
        FinanceDepertment obj = dod.getRandomFinanceDepertment();
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to provide an identifier", id);
        obj = FinanceDepertment.findFinanceDepertment(id);
        Assert.assertNotNull("Find method for 'FinanceDepertment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FinanceDepertment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FinanceDepertmentIntegrationTest.testFindAllFinanceDepertments() {
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to initialize correctly", dod.getRandomFinanceDepertment());
        long count = FinanceDepertment.countFinanceDepertments();
        Assert.assertTrue("Too expensive to perform a find all test for 'FinanceDepertment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FinanceDepertment> result = FinanceDepertment.findAllFinanceDepertments();
        Assert.assertNotNull("Find all method for 'FinanceDepertment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FinanceDepertment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FinanceDepertmentIntegrationTest.testFindFinanceDepertmentEntries() {
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to initialize correctly", dod.getRandomFinanceDepertment());
        long count = FinanceDepertment.countFinanceDepertments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FinanceDepertment> result = FinanceDepertment.findFinanceDepertmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FinanceDepertment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FinanceDepertment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FinanceDepertmentIntegrationTest.testFlush() {
        FinanceDepertment obj = dod.getRandomFinanceDepertment();
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to provide an identifier", id);
        obj = FinanceDepertment.findFinanceDepertment(id);
        Assert.assertNotNull("Find method for 'FinanceDepertment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFinanceDepertment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FinanceDepertment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FinanceDepertmentIntegrationTest.testMergeUpdate() {
        FinanceDepertment obj = dod.getRandomFinanceDepertment();
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to provide an identifier", id);
        obj = FinanceDepertment.findFinanceDepertment(id);
        boolean modified =  dod.modifyFinanceDepertment(obj);
        Integer currentVersion = obj.getVersion();
        FinanceDepertment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FinanceDepertment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FinanceDepertmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to initialize correctly", dod.getRandomFinanceDepertment());
        FinanceDepertment obj = dod.getNewTransientFinanceDepertment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FinanceDepertment' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'FinanceDepertment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FinanceDepertmentIntegrationTest.testRemove() {
        FinanceDepertment obj = dod.getRandomFinanceDepertment();
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinanceDepertment' failed to provide an identifier", id);
        obj = FinanceDepertment.findFinanceDepertment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FinanceDepertment' with identifier '" + id + "'", FinanceDepertment.findFinanceDepertment(id));
    }
    
}
