// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package project.group16.entity;

import org.springframework.beans.factory.annotation.Configurable;
import project.group16.entity.FinanceDepertmentIntegrationTest;

privileged aspect FinanceDepertmentIntegrationTest_Roo_Configurable {
    
    declare @type: FinanceDepertmentIntegrationTest: @Configurable;
    
}
