// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package project.group16.entity;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import project.group16.entity.FinanceDepartment;
import project.group16.entity.FinanceDepartmentDataOnDemand;
import project.group16.entity.FinanceDepartmentIntegrationTest;

privileged aspect FinanceDepartmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FinanceDepartmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FinanceDepartmentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FinanceDepartmentIntegrationTest: @Transactional;
    
    @Autowired
    private FinanceDepartmentDataOnDemand FinanceDepartmentIntegrationTest.dod;
    
    @Test
    public void FinanceDepartmentIntegrationTest.testCountFinanceDepartments() {
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to initialize correctly", dod.getRandomFinanceDepartment());
        long count = FinanceDepartment.countFinanceDepartments();
        Assert.assertTrue("Counter for 'FinanceDepartment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FinanceDepartmentIntegrationTest.testFindFinanceDepartment() {
        FinanceDepartment obj = dod.getRandomFinanceDepartment();
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to provide an identifier", id);
        obj = FinanceDepartment.findFinanceDepartment(id);
        Assert.assertNotNull("Find method for 'FinanceDepartment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FinanceDepartment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FinanceDepartmentIntegrationTest.testFindAllFinanceDepartments() {
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to initialize correctly", dod.getRandomFinanceDepartment());
        long count = FinanceDepartment.countFinanceDepartments();
        Assert.assertTrue("Too expensive to perform a find all test for 'FinanceDepartment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FinanceDepartment> result = FinanceDepartment.findAllFinanceDepartments();
        Assert.assertNotNull("Find all method for 'FinanceDepartment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FinanceDepartment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FinanceDepartmentIntegrationTest.testFindFinanceDepartmentEntries() {
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to initialize correctly", dod.getRandomFinanceDepartment());
        long count = FinanceDepartment.countFinanceDepartments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FinanceDepartment> result = FinanceDepartment.findFinanceDepartmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FinanceDepartment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FinanceDepartment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FinanceDepartmentIntegrationTest.testFlush() {
        FinanceDepartment obj = dod.getRandomFinanceDepartment();
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to provide an identifier", id);
        obj = FinanceDepartment.findFinanceDepartment(id);
        Assert.assertNotNull("Find method for 'FinanceDepartment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFinanceDepartment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FinanceDepartment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FinanceDepartmentIntegrationTest.testMergeUpdate() {
        FinanceDepartment obj = dod.getRandomFinanceDepartment();
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to provide an identifier", id);
        obj = FinanceDepartment.findFinanceDepartment(id);
        boolean modified =  dod.modifyFinanceDepartment(obj);
        Integer currentVersion = obj.getVersion();
        FinanceDepartment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FinanceDepartment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FinanceDepartmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to initialize correctly", dod.getRandomFinanceDepartment());
        FinanceDepartment obj = dod.getNewTransientFinanceDepartment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FinanceDepartment' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'FinanceDepartment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FinanceDepartmentIntegrationTest.testRemove() {
        FinanceDepartment obj = dod.getRandomFinanceDepartment();
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinanceDepartment' failed to provide an identifier", id);
        obj = FinanceDepartment.findFinanceDepartment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FinanceDepartment' with identifier '" + id + "'", FinanceDepartment.findFinanceDepartment(id));
    }
    
}
