// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package project.group16.entity;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import project.group16.entity.FinanceDepertment;
import project.group16.entity.FinanceDepertmentDataOnDemand;

privileged aspect FinanceDepertmentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FinanceDepertmentDataOnDemand: @Component;
    
    private Random FinanceDepertmentDataOnDemand.rnd = new SecureRandom();
    
    private List<FinanceDepertment> FinanceDepertmentDataOnDemand.data;
    
    public FinanceDepertment FinanceDepertmentDataOnDemand.getNewTransientFinanceDepertment(int index) {
        FinanceDepertment obj = new FinanceDepertment();
        return obj;
    }
    
    public FinanceDepertment FinanceDepertmentDataOnDemand.getSpecificFinanceDepertment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FinanceDepertment obj = data.get(index);
        Long id = obj.getId();
        return FinanceDepertment.findFinanceDepertment(id);
    }
    
    public FinanceDepertment FinanceDepertmentDataOnDemand.getRandomFinanceDepertment() {
        init();
        FinanceDepertment obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return FinanceDepertment.findFinanceDepertment(id);
    }
    
    public boolean FinanceDepertmentDataOnDemand.modifyFinanceDepertment(FinanceDepertment obj) {
        return false;
    }
    
    public void FinanceDepertmentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = FinanceDepertment.findFinanceDepertmentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FinanceDepertment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FinanceDepertment>();
        for (int i = 0; i < 10; i++) {
            FinanceDepertment obj = getNewTransientFinanceDepertment(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
