// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package project.group16.entity;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import project.group16.entity.FinanceDepartment;
import project.group16.entity.FinanceDepartmentDataOnDemand;

privileged aspect FinanceDepartmentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FinanceDepartmentDataOnDemand: @Component;
    
    private Random FinanceDepartmentDataOnDemand.rnd = new SecureRandom();
    
    private List<FinanceDepartment> FinanceDepartmentDataOnDemand.data;
    
    public FinanceDepartment FinanceDepartmentDataOnDemand.getNewTransientFinanceDepartment(int index) {
        FinanceDepartment obj = new FinanceDepartment();
        return obj;
    }
    
    public FinanceDepartment FinanceDepartmentDataOnDemand.getSpecificFinanceDepartment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FinanceDepartment obj = data.get(index);
        Long id = obj.getId();
        return FinanceDepartment.findFinanceDepartment(id);
    }
    
    public FinanceDepartment FinanceDepartmentDataOnDemand.getRandomFinanceDepartment() {
        init();
        FinanceDepartment obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return FinanceDepartment.findFinanceDepartment(id);
    }
    
    public boolean FinanceDepartmentDataOnDemand.modifyFinanceDepartment(FinanceDepartment obj) {
        return false;
    }
    
    public void FinanceDepartmentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = FinanceDepartment.findFinanceDepartmentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FinanceDepartment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FinanceDepartment>();
        for (int i = 0; i < 10; i++) {
            FinanceDepartment obj = getNewTransientFinanceDepartment(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
