// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package project.group16.entity;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import project.group16.entity.RequisitionAllowance;
import project.group16.entity.RequisitionAllowanceDataOnDemand;

privileged aspect RequisitionAllowanceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RequisitionAllowanceDataOnDemand: @Component;
    
    private Random RequisitionAllowanceDataOnDemand.rnd = new SecureRandom();
    
    private List<RequisitionAllowance> RequisitionAllowanceDataOnDemand.data;
    
    public RequisitionAllowance RequisitionAllowanceDataOnDemand.getNewTransientRequisitionAllowance(int index) {
        RequisitionAllowance obj = new RequisitionAllowance();
        setDateWork(obj, index);
        return obj;
    }
    
    public void RequisitionAllowanceDataOnDemand.setDateWork(RequisitionAllowance obj, int index) {
        Date dateWork = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateWork(dateWork);
    }
    
    public RequisitionAllowance RequisitionAllowanceDataOnDemand.getSpecificRequisitionAllowance(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        RequisitionAllowance obj = data.get(index);
        Long id = obj.getId();
        return RequisitionAllowance.findRequisitionAllowance(id);
    }
    
    public RequisitionAllowance RequisitionAllowanceDataOnDemand.getRandomRequisitionAllowance() {
        init();
        RequisitionAllowance obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return RequisitionAllowance.findRequisitionAllowance(id);
    }
    
    public boolean RequisitionAllowanceDataOnDemand.modifyRequisitionAllowance(RequisitionAllowance obj) {
        return false;
    }
    
    public void RequisitionAllowanceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = RequisitionAllowance.findRequisitionAllowanceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'RequisitionAllowance' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<RequisitionAllowance>();
        for (int i = 0; i < 10; i++) {
            RequisitionAllowance obj = getNewTransientRequisitionAllowance(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
