// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package project.group16.entity;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import project.group16.entity.RequisitionAllowance;
import project.group16.entity.RequisitionAllowanceDataOnDemand;
import project.group16.entity.RequisitionAllowanceIntegrationTest;

privileged aspect RequisitionAllowanceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RequisitionAllowanceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RequisitionAllowanceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RequisitionAllowanceIntegrationTest: @Transactional;
    
    @Autowired
    private RequisitionAllowanceDataOnDemand RequisitionAllowanceIntegrationTest.dod;
    
    @Test
    public void RequisitionAllowanceIntegrationTest.testCountRequisitionAllowances() {
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to initialize correctly", dod.getRandomRequisitionAllowance());
        long count = RequisitionAllowance.countRequisitionAllowances();
        Assert.assertTrue("Counter for 'RequisitionAllowance' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RequisitionAllowanceIntegrationTest.testFindRequisitionAllowance() {
        RequisitionAllowance obj = dod.getRandomRequisitionAllowance();
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to provide an identifier", id);
        obj = RequisitionAllowance.findRequisitionAllowance(id);
        Assert.assertNotNull("Find method for 'RequisitionAllowance' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RequisitionAllowance' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RequisitionAllowanceIntegrationTest.testFindAllRequisitionAllowances() {
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to initialize correctly", dod.getRandomRequisitionAllowance());
        long count = RequisitionAllowance.countRequisitionAllowances();
        Assert.assertTrue("Too expensive to perform a find all test for 'RequisitionAllowance', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RequisitionAllowance> result = RequisitionAllowance.findAllRequisitionAllowances();
        Assert.assertNotNull("Find all method for 'RequisitionAllowance' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RequisitionAllowance' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RequisitionAllowanceIntegrationTest.testFindRequisitionAllowanceEntries() {
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to initialize correctly", dod.getRandomRequisitionAllowance());
        long count = RequisitionAllowance.countRequisitionAllowances();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RequisitionAllowance> result = RequisitionAllowance.findRequisitionAllowanceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RequisitionAllowance' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RequisitionAllowance' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RequisitionAllowanceIntegrationTest.testFlush() {
        RequisitionAllowance obj = dod.getRandomRequisitionAllowance();
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to provide an identifier", id);
        obj = RequisitionAllowance.findRequisitionAllowance(id);
        Assert.assertNotNull("Find method for 'RequisitionAllowance' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRequisitionAllowance(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RequisitionAllowance' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RequisitionAllowanceIntegrationTest.testMergeUpdate() {
        RequisitionAllowance obj = dod.getRandomRequisitionAllowance();
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to provide an identifier", id);
        obj = RequisitionAllowance.findRequisitionAllowance(id);
        boolean modified =  dod.modifyRequisitionAllowance(obj);
        Integer currentVersion = obj.getVersion();
        RequisitionAllowance merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RequisitionAllowance' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RequisitionAllowanceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to initialize correctly", dod.getRandomRequisitionAllowance());
        RequisitionAllowance obj = dod.getNewTransientRequisitionAllowance(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RequisitionAllowance' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'RequisitionAllowance' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RequisitionAllowanceIntegrationTest.testRemove() {
        RequisitionAllowance obj = dod.getRandomRequisitionAllowance();
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequisitionAllowance' failed to provide an identifier", id);
        obj = RequisitionAllowance.findRequisitionAllowance(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RequisitionAllowance' with identifier '" + id + "'", RequisitionAllowance.findRequisitionAllowance(id));
    }
    
}
